### PR TITLE
Fix hdr_histogram compilation error

### LINKED ISSUE #51: deps/hdr_histogram/hdr_histogram.c error
get_value_from_idx_up_to_count函数拷贝的时候多了一份代码导致编译错误

### PR DESCRIPTION
**Pull request by enjoy-binbin**
It looks like there was a conflict when merging and it was not resolved correctly.
Copy the entire deps from Redis 7.0.4 to fix this.

Fixes #51, it was introduced in #8.

### CODE REVIEW

**Comment by enjoy-binbin** [comment]
@OTZ-alt FYI
测了现在可以编译成功

**Review by ncghost1 — APPROVED** [review]
